### ISSUE TITLE
Build failing on Ubuntu 18.04

### ISSUE THREAD

**Issue by mrwesleycrusher** [carla-simulator/map#7]
Hello, I am trying to build this library so I can build the intel ad-rss-lib library.
I am configuring my build environment from a fresh ubuntu 18.04 installation via the following ansible playbook

```
---
- name: Configure CARLA with RSS 
  hosts: ubuntu18
  remote_user: ansible
  become: yes
  tasks:
    - name: apt full upgrade
      apt:
        upgrade: full
    
    - name: install build dependencies
      apt:
        pkg: 
            - htop
            - wget 
            - git 
            - libgtest-dev 
            - libpython-dev
            - castxml
            - python3-dev
            - python3-pip
            - libboost-all-dev 
            - libpugixml-dev
            - libproj-dev
            - proj-bin
            - cmake 
            - libgtest-dev
            - libosmium2-dev
            - make 
            - curl
            - gnupg2
            - lsb-release
            - build-essential 
            - doxygen 
            - graphviz
            - python-pip
            - python-dev

        state: latest

    - name: add vscode key
      apt_key: 
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present
    
    - name: add vscode repo
      apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
        state: present
     
    - name: install code
      apt:
        name: code
        update_cache: yes
        state: latest

    - name: install pygccxml (python3)
      pip:
        name: pygccxml
        executable: pip3
        
    
    - name: install pyplusplus (python3)
      pip: 
        name: https://bitbucket.org/ompl/pyplusplus/get/1.8.1.zip
        executable: pip3
        state: latest

    - name: install pygccxml (python2)
      pip:
        name: pygccxml
        executable: pip
          
      
    - name: install pyplusplus (python2)
      pip: 
        name: https://bitbucket.org/ompl/pyplusplus/get/1.8.1.zip
        executable: pip
        state: latest

    - name: get spblog
      git:
        repo: https://github.com/gabime/spdlog.git
        dest: /home/ansible/Documents/spdlog/
        clone: yes
    
    - name: build spdlog
      shell: 
        cmd: mkdir -p build && cd build && cmake .. && make -j7
        chdir: /home/ansible/Documents/spdlog/

    - name: add ROS 2 repo key
      apt_key:
        url: https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc
        state: present

    - name: add ROS 2 repo
      apt_repository:
        repo: deb http://packages.ros.org/ros2/ubuntu bionic main
        state: present
        update_cache: yes
    
    - name: install the colcon-core package
      apt:
        name: python3-colcon-common-extensions
        update_cache: yes
        state: latest

    - name: get carla-simulator/map meta repo
      git:
        repo: https://github.com/carla-simulator/map.git
        dest: /home/ansible/Documents/carla_map/
        clone: yes

    - name: update map deps
      shell:
        cmd: git submodule update --init
        chdir: /home/ansible/Documents/carla_map/

    - name: colcon build of carla map lib 
      shell:
        cmd: sudo colcon build --metas colcon_python.meta 
        chdir: /home/ansible/Documents/carla_map/
````

but on the colcon build line, I get the attached build error:
[error.txt](https://github.com/carla-simulator/map/files/4432992/error.txt)

The issue seems to be coming from the gtest dependency, more specifically:
````
/home/ansible/Documents/carla_map/ad_map_access/impl/tests/generated/ad/map/access/PartitionIdTests.cpp:21:3:   required from here
/usr/src/googletest/googletest/include/gtest/gtest.h:1392:11: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
   if (lhs == rhs) {
       ~~~~^~~~~~
In file included from /home/ansible/Documents/carla_map/ad_map_access/impl/tests/route/RoutePlanningTests.cpp:17:0:
/usr/src/googletest/googletest/include/gtest/gtest.h: In instantiation of ‘testing::AssertionResult testing::internal::CmpHelperEQ(const char*, const char*, const T1&, const T2&) [with T1 = long unsigned int; T2 = int]’:
/usr/src/googletest/googletest/include/gtest/gtest.h:1421:23:   required from ‘static testing::AssertionResult testing::internal::EqHelper<lhs_is_null_literal>::Compare(const char*, const char*, const T1&, const T2&) [with T1 = long unsigned int; T2 = int; bool lhs_is_null_literal = false]’
/home/ansible/Documents/carla_map/ad_map_access/impl/tests/route/RoutePlanningTests.cpp:213:7:   required from here
/usr/src/googletest/googletest/include/gtest/gtest.h:1392:11: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
   if (lhs == rhs) {
````
What is wrong with my build?
